### ISSUE TITLE
Could not convert data to boolean. Expected "true", "false", "1" or "0", but got "-1".

### ISSUE THREAD

**Issue by tyurderi** [next-sentence/afterbuy-sdk#2]
I receive this exception when calling `Request::getShopProducts()` because for example `MergeStock`and `TitleReplace`got a wrong value.

I fixed this myself by changing the annotation for the related attributes.

I would love when you have a nice fix for this.

Thank you

**Comment by Tardog** [comment]
Hi! I ran into the same issues. Did you discover any other attributes with wrong type declarations?

**Comment by Tardog** [comment]
This should be fixed now in master. Can you confirm it works for you?
