### ISSUE TITLE
Pagination on GetShopProducts request not usable

### ISSUE THREAD

**Issue by Tardog** [next-sentence/afterbuy-sdk#3]
When pagination is enabled the getShopProducts() call, the API ignores the setting and does not return any pagination information.

While the documentation claims the PaginationEnabled settings is supposed to be a boolean, the API does not seem to accept boolean values. Changing the seralized type to integer allows pagination to work as intended.

I was able to test this successfully and can create a pull request, if you want.

**Comment by next-sentence** [comment]
thanks)
